[project]
name = "nahual-transformers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "timm>=1.0.22",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
